# Synthetic Q&A Generation — UR5e Cobot + Bridgeport Mill

Generates 100 new Q&A pairs (50 per machine) by:
- Randomly sampling example Q&A pairs from the golden sets as few-shot examples
- Randomly sampling text chunks from the cropped PDFs as grounding context
- Using the LLM to generate new, diverse Q&A pairs grounded in the manuals

**Output:** `data/QA/synthetic_qa_cobot_mill.csv` — columns: `machine, question, gold_answer`

In [1]:
import sys
import random
import json
import re
from pathlib import Path

import pandas as pd
from openai import OpenAI
from langchain_community.document_loaders import PyMuPDFLoader

sys.path.insert(0, str(Path("..").resolve()))

from system.rag.rag_utils import _format_sources_xml
from system.utils import EnvironmentConfig
from system.preprocess import PDFPreprocessor

/Users/ryan/Desktop/Work/SIGHT/safety_rag_eval_ryan/venv/lib/python3.10/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.5.0) or chardet (7.0.1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(

## Load Golden Sets

In [2]:
COBOT_QA_PATH = Path("../data/QA/COBOT/Final_COBOT_QA.csv")
MILL_QA_PATH  = Path("../data/QA/MILL/Mill Feedback Accepted.csv")

cobot_golden = (
    pd.read_csv(COBOT_QA_PATH)
    .dropna(subset=["question", "gold_answer"])
    .reset_index(drop=True)
)
mill_golden = (
    pd.read_csv(MILL_QA_PATH)
    .dropna(subset=["question", "gold_answer"])
    .reset_index(drop=True)
)

print(f"COBOT golden set : {len(cobot_golden)} rows")
print(f"Mill  golden set : {len(mill_golden)} rows")
display(cobot_golden.head(3))
display(mill_golden.head(3))

COBOT golden set : 32 rows
Mill  golden set : 51 rows

,question,gold_answer
0,What safety modes does the robot arm have?,The robot arm has three safety modes. Normal m...
1,What happens if my robot stopped in 1000ms whe...,The robot arm will enter recovery mode because...
2,What mode do I need to be in to load a program?,You need to be in Automatic Mode to load and e...

,question,gold_answer
0,What are the 5 main categories of safety label...,DANGER\nDANGER indicates a hazardous situation...
1,What are the safety labels used in the birdgep...,DANGER(Red with white text)\nDANGER indicates ...
2,I am trying to mount the Spindle Guard onto th...,There are two tapped holes in the nose cap of ...

## Crop PDFs + Extract Text

Reused from `system/main_long_context.ipynb` — same crop parameters.

In [3]:
PDF_DIR = Path("../data/input/input_pdfs")

TARGETS = {
    "Mill (Bridgeport)": {
        "path": PDF_DIR / "Bridgeport Series 1 Milling manual with schematics.pdf",
        "crop_top": 0.04, "crop_bottom": 0.075, "crop_left": 0.0, "crop_right": 0.0,
    },
    "UR5e Cobot": {
        "path": PDF_DIR / "UR5e_Universal_Robots User Manual.pdf",
        "crop_percent": 0.075,
    },
}

def load_pdf_as_text(path) -> str:
    pages = PyMuPDFLoader(str(path)).load()
    return "\n\n".join(p.page_content for p in pages).strip()

OUTPUT_DIR = Path("../data/input/cropped_pdfs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CROPPED = {}
for label, cfg in TARGETS.items():
    out = OUTPUT_DIR / f"cropped_{cfg['path'].name}"
    PDFPreprocessor.crop_pdf(
        cfg["path"], out,
        crop_percent=cfg.get("crop_percent", 0.075),
        crop_top=cfg.get("crop_top"),
        crop_bottom=cfg.get("crop_bottom"),
        crop_left=cfg.get("crop_left"),
        crop_right=cfg.get("crop_right"),
    )
    CROPPED[label] = out
    print(f"Cropped {label} -> {out.name}")

mill_cropped_text = load_pdf_as_text(CROPPED["Mill (Bridgeport)"])
ur5e_cropped_text = load_pdf_as_text(CROPPED["UR5e Cobot"])

print(f"\nMill  (cropped): {len(mill_cropped_text):,} chars")
print(f"UR5e  (cropped): {len(ur5e_cropped_text):,} chars")

Cropped Mill (Bridgeport) -> cropped_Bridgeport Series 1 Milling manual with schematics.pdf
Cropped UR5e Cobot -> cropped_UR5e_Universal_Robots User Manual.pdf

Mill  (cropped): 121,502 chars
UR5e  (cropped): 253,244 chars

## Chunk Document Text

Split each cropped PDF into overlapping ~2000-char chunks. Each chunk acts as a retrieved page that the LLM uses as grounding context.

In [4]:
def chunk_text(text: str, chunk_size: int = 2000, overlap: int = 200) -> list:
    """Split text into overlapping fixed-size chunks."""
    chunks = []
    start = 0
    while start < len(text):
        chunks.append(text[start : start + chunk_size])
        start += chunk_size - overlap
    return chunks

mill_chunks  = chunk_text(mill_cropped_text)
ur5e_chunks  = chunk_text(ur5e_cropped_text)

print(f"Mill  chunks : {len(mill_chunks)}")
print(f"UR5e  chunks : {len(ur5e_chunks)}")

Mill  chunks : 68
UR5e  chunks : 141

## Synthetic QA Generation

Each call to `generate_synthetic_qa()` independently randomizes:
- **`n_examples`** example Q&A pairs drawn from the golden set (few-shot style)
- **`n_chunks`** text chunks drawn from the PDF (grounding context)

Chunks are formatted via `_format_sources_xml()` (reused from `system/rag/rag_utils.py`) so the LLM sees the same structured XML format used during evaluation.

In [8]:
SYNTH_SYSTEM_PROMPT = """\
You are an expert at creating safety and operational Q&A pairs for industrial equipment manuals.
You will be given:
  1. Example Q&A pairs that show the expected style and scope.
  2. Source passages from the machine manual.

Your task: generate {n} NEW question-answer pairs.

Rules:
- Every question must be directly answerable from the provided source passages.
- Answers must be concise (1–5 sentences or short bullet points), mirroring manual terminology.
- Do NOT duplicate or closely paraphrase the example questions.
- Question/answer pairs should range from easy to hard. 
- Cover diverse topics: safety procedures, operating steps, warnings, maintenance, specifications.
- Output ONLY a valid JSON array with no extra text:
  [{{"question": "...", "gold_answer": "..."}}, ...]
"""


def generate_synthetic_qa(
    client: OpenAI,
    document_chunks: list,
    golden_df: pd.DataFrame,
    machine_name: str,
    n_examples: int = 6,
    n_chunks: int = 5,
    n_generate: int = 5,
    model: str = "gpt-5.4-2026-03-05",
) -> list:
    """
    Generate `n_generate` synthetic Q&A pairs for `machine_name`.

    Randomizes both the few-shot examples drawn from the golden set
    and the document chunks used as grounding context on every call.

    Reuses `_format_sources_xml()` from system/rag/rag_utils.py to
    format the document chunks in the same XML structure used during
    RAG evaluation.
    """
    # 1. Randomly sample few-shot examples from the golden set
    examples = golden_df.sample(n=min(n_examples, len(golden_df)))
    examples_text = "\n\n".join(
        f"Q: {row.question}\nA: {row.gold_answer}"
        for _, row in examples.iterrows()
    )

    # 2. Randomly sample document chunks and build hits in the expected schema
    selected = random.sample(document_chunks, min(n_chunks, len(document_chunks)))
    hits = [
        {"filename": machine_name, "file_id": "", "score": None, "text": chunk}
        for chunk in selected
    ]

    # 3. Format chunks as XML using the existing rag_utils helper
    sources_xml = _format_sources_xml(hits, max_chars_per_content=2000)

    # 4. Build messages and call LLM (same pattern as _ask_with_sources in rag_utils.py)
    system_msg = SYNTH_SYSTEM_PROMPT.format(n=n_generate)
    user_msg = (
        f"Machine: {machine_name}\n\n"
        f"Example Q&A pairs (do NOT duplicate):\n{examples_text}\n\n"
        f"Generate {n_generate} new Q&A pairs based on the source passages below."
    )

    resp = client.responses.create(
        model=model,
        input=[
            {"role": "system",  "content": system_msg},
            {"role": "user",    "content": user_msg},
            {"role": "user",    "content": f"Source passages:\n{sources_xml}"},
        ],
        reasoning={"effort": "low"},
        max_output_tokens=3000,
    )

    # 5. Parse JSON array from response
    raw = getattr(resp, "output_text", "") or ""
    match = re.search(r"\[.*\]", raw, re.DOTALL)
    if not match:
        print(f"  [WARN] Could not parse JSON from response for {machine_name}")
        return []
    try:
        pairs = json.loads(match.group())
    except json.JSONDecodeError as e:
        print(f"  [WARN] JSON decode error: {e}")
        return []

    return [
        {
            "machine": machine_name,
            "question": p["question"],
            "gold_answer": p["gold_answer"],
        }
        for p in pairs
        if isinstance(p, dict) and "question" in p and "gold_answer" in p
    ]


print("generate_synthetic_qa() defined.")

generate_synthetic_qa() defined.

## Generate — UR5e Cobot (target: 50 pairs)

10 batches × 5 pairs per batch = 50 target.

In [11]:
client = OpenAI()

ur5e_results = []
for i in range(10):
    batch = generate_synthetic_qa(
        client,
        document_chunks=ur5e_chunks,
        golden_df=cobot_golden,
        machine_name="UR5e Cobot",
    )
    ur5e_results.extend(batch)
    print(f"  Batch {i+1:02d}: +{len(batch)} pairs  (running total: {len(ur5e_results)})")

print(f"\nUR5e Cobot total: {len(ur5e_results)} Q&A pairs generated")

  Batch 01: +5 pairs  (running total: 5)
  Batch 02: +5 pairs  (running total: 10)
  Batch 03: +5 pairs  (running total: 15)
  Batch 04: +5 pairs  (running total: 20)
  Batch 05: +5 pairs  (running total: 25)
  Batch 06: +5 pairs  (running total: 30)
  Batch 07: +5 pairs  (running total: 35)
  Batch 08: +5 pairs  (running total: 40)
  Batch 09: +5 pairs  (running total: 45)
  Batch 10: +5 pairs  (running total: 50)

UR5e Cobot total: 50 Q&A pairs generated

In [12]:
ur5e_results

[{'machine': 'UR5e Cobot',
  'question': 'What must be provided as part of the electrical installation for the UR5e Control Box mains connection?',
  'gold_answer': 'Provide:\n- Connection to ground\n- Main fuse\n- Residual current device\n- A lockable switch in the OFF position\nA main switch shall also be installed to power off all equipment in the robot application as an easy means for lockout.'},
 {'machine': 'UR5e Cobot',
  'question': 'What should you do before turning on the robot arm after connecting the Robot Cable to the Control Box?',
  'gold_answer': 'Plug and lock the cable from the robot into the connector at the bottom of the Control Box, then twist the connector twice to ensure it is properly locked. Do not disconnect the Robot Cable when the robot arm is turned on, and do not extend or modify the original Robot Cable.'},
 {'machine': 'UR5e Cobot',
  'question': 'Why is it important to set the robot arm mounting correctly in the installation settings?',
  'gold_answer': 'Specifying the mounting makes the Robot arm appear correctly on screen and tells the controller the direction of gravity. If mounted incorrectly, the robot may stop frequently and/or move when pressing the Freedrive button.'},
 {'machine': 'UR5e Cobot',
  'question': 'What actions can PolyScope take if the robot loses EtherNet/IP Scanner Device or PROFINET IO-Controller connection during a program?',
  'gold_answer': 'The selectable actions are None, Pause, or Stop. None lets the program continue, Pause pauses the current program and resumes from where it stopped, and Stop stops the current program.'},
 {'machine': 'UR5e Cobot',
  'question': 'What are the input voltage range, input frequency range, and nominal operating power for the UR5e Control Box?',
  'gold_answer': 'Input voltage: 90–264 VAC. Input frequency: 47–440 Hz. Nominal operating power: typ. 150 W, max. 325 W.'},
 {'machine': 'UR5e Cobot',
  'question': 'How do you configure the robot to operate without a Teach Pendant?',
  'gold_answer': 'In Header, tap Installation, then Safety > Hardware. Enter the Safety password and unlock the screen, deselect Teach Pendant, then press Save and restart to implement the changes.'},
 {'machine': 'UR5e Cobot',
  'question': 'What safety precaution is required when the Teach Pendant is detached or disconnected?',
  'gold_answer': 'The Emergency Stop button on the Teach Pendant is no longer active. You must remove the Teach Pendant from the vicinity of the robot.'},
 {'machine': 'UR5e Cobot',
  'question': 'When does the Safety Checksum change, and how should it be read?',
  'gold_answer': 'The Safety Checksum changes when Safety Functions settings are changed, and only after the Safety Configuration changes are applied. A four-digit checksum is read top to bottom and left to right; an eight-digit checksum is read left to right, top row first.'},
 {'machine': 'UR5e Cobot',
  'question': 'What does the MODBUS Sequential mode do, and when might it be useful?',
  'gold_answer': 'Sequential mode forces the MODBUS client to wait for a response before sending the next request. It is required by some fieldbus units and can help when multiple signals and higher request frequency cause signal disconnects.'},
 {'machine': 'UR5e Cobot',
  'question': 'What is the warning for tool analog inputs in current mode, and what are the current-mode electrical limits?',
  'gold_answer': 'Analog Inputs are not protected against over voltage in current mode, and exceeding the specification can permanently damage the input. In current mode, input voltage is -0.5 to 5.0 V and input current is -2.5 to 25 mA.'},
 {'machine': 'UR5e Cobot',
  'question': 'What happens in Recovery mode, and what safety warning applies when moving the robot arm in this mode?',
  'gold_answer': 'Recovery mode activates when an active safety limit is violated, and the robot arm performs a Stop Category 0. If a safety limit is already violated at power-on, the robot starts in Recovery mode so it can be moved back within limits. In Recovery mode, joint position, tool position, and tool orientation limits are disabled, so caution is required.'},
 {'machine': 'UR5e Cobot',
  'question': 'How many safety planes can be defined, and what must be created before configuring them?',
  'gold_answer': 'You can define up to eight safety planes. Before configuring safety planes, you must define a feature in the robot installation so it can be copied into the safety plane screen and configured.'},
 {'machine': 'UR5e Cobot',
  'question': 'What is the difference between Emergency Stop and Safeguard Stop in terms of drive power, reset, and stop category?',
  'gold_answer': 'Emergency Stop turns drive power off, requires a manual reset, and is Stop Category 1. Safeguard Stop leaves drive power on, allows automatic or manual reset, and is Stop Category 2.'},
 {'machine': 'UR5e Cobot',
  'question': 'When should safety functions be verified and tested?',
  'gold_answer': 'Safety functions shall be verified before putting the robot into operation. They shall also be tested regularly.'},
 {'machine': 'UR5e Cobot',
  'question': 'What are the voltage and current requirements for the external 24V input used to supply the I/O?',
  'gold_answer': 'For the external 24V input [24V - 0V], the voltage must be 20–29 V, with 24 V typical. The maximum current is 6 A.'},
 {'machine': 'UR5e Cobot',
  'question': 'How do you set the Administrator password on the UR5e, and what is the default current password?',
  'gold_answer': 'Go to Header > Hamburger menu > Settings > Password > Admin. Enter the current default password "easybot," then create and confirm a new password and tap Apply.'},
 {'machine': 'UR5e Cobot',
  'question': 'What warning does the manual give about losing the Admin password?',
  'gold_answer': 'The manual warns that you cannot recover a lost Admin password. Appropriate steps must be taken to ensure the admin password is not lost.'},
 {'machine': 'UR5e Cobot',
  'question': 'What personal protective equipment and precautions are recommended when handling grease during maintenance?',
  'gold_answer': 'Use oil-resistant nitrile gloves and eye protection. Ensure the area is well ventilated, keep food and beverages away, have an eyewash station nearby, and do not ingest the grease.'},
 {'machine': 'UR5e Cobot',
  'question': 'Under what conditions is the robot considered to be in the Safe Home Position?',
  'gold_answer': 'The robot is in the Safe Home Position when it is at rest, meaning not moving, and in the position defined as the Safe Home Position.'},
 {'machine': 'UR5e Cobot',
  'question': 'What happens if the safe home output is activated when the robot is not in the configured safe home position?',
  'gold_answer': 'A stop category 0 is initiated if the output is activated when the robot is not in the configured and monitored safe home position.'},
 {'machine': 'UR5e Cobot',
  'question': 'How do you start a robot program from a specific node in the Program tree?',
  'gold_answer': '1. In the Program tree, select a node.\n2. In the Footer, tap Play.\n3. Select Play from Selection to run the program from that node.'},
 {'machine': 'UR5e Cobot',
  'question': 'What limitations apply when using Play from Selection?',
  'gold_answer': 'It can start only from a node in the robot Program tree. It cannot be used with a thread because threads always start from the beginning. If the selected node cannot run, or an unassigned variable is encountered, the program stops and displays an error.'},
 {'machine': 'UR5e Cobot',
  'question': 'What warning is given about modifying the robot or e-Series end caps?',
  'gold_answer': 'Do not modify the robot and do not modify or alter e-Series end caps. A modification can create unforeseen hazards. Authorized disassembling and reassembling shall be done at a UR service center, or according to the newest relevant service manuals by skilled persons.'},
 {'machine': 'UR5e Cobot',
  'question': 'What must the application risk assessment include regarding robot motion?',
  'gold_answer': "It shall include the risks associated with the application's reach, motion, payload, and speed of the robot, end effector, and workpiece. Failure to consider these added risks can result in injury or death."},
 {'machine': 'UR5e Cobot',
  'question': 'In Tool Position Restriction, what is the default Tool_1 configuration and how can it be reset to the tool flange?',
  'gold_answer': 'Tool_1 is the default tool with x=0.0, y=0.0, z=0.0, and radius=0.0, representing the robot tool flange. Under Copy TCP, select Tool Flange to cause the tool values to go back to 0. A default sphere is defined at the tool flange.'},
 {'machine': 'UR5e Cobot',
  'question': 'How do you add and configure a Set Payload command in a robot program?',
  'gold_answer': '1. Select the place or node in the program where you want to add a Set command.\n2. Under Basic, tap Set Payload.\n3. In Select Payload, choose an existing payload or select Custom Payload and enter the mass and CoG fields.\nYou can also use Set Now to set the node values as the active payload.'},
 {'machine': 'UR5e Cobot',
  'question': 'When is Payload Transition Time recommended, and what does it do?',
  'gold_answer': 'Payload Transition Time is recommended when picking up or releasing heavy objects or when using a vacuum gripper. Setting the transition time larger than zero prevents the robot from doing a small jump when the payload changes, while the program continues during the adjustment.'},
 {'machine': 'UR5e Cobot',
  'question': 'What warning is given about using Factory Presets for Robot Limits?',
  'gold_answer': 'The slider values in Factory Presets are only suggestions and do not substitute a proper risk assessment.'},
 {'machine': 'UR5e Cobot',
  'question': 'Which robot behaviors can be limited in the Custom Robot Limits settings?',
  'gold_answer': 'Custom Robot Limits can limit: Power, Momentum, Stopping Time, Stopping Distance, Tool Speed, Tool Force, Elbow Speed, and Elbow Force.'},
 {'machine': 'UR5e Cobot',
  'question': 'What is the elbow restriction diameter for a UR5e when using safety planes?',
  'gold_answer': 'For a UR5e, the elbow restriction diameter is 0.13 m.'},
 {'machine': 'UR5e Cobot',
  'question': 'What happens when Dual Pin Power is enabled for the tool output configuration?',
  'gold_answer': 'Dual Pin Power is used as a source of power for the tool. Enabling Dual Pin Power disables the default tool digital outputs.'},
 {'machine': 'UR5e Cobot',
  'question': 'What should you do after changing the tool output configuration so the new setup is not lost?',
  'gold_answer': 'After verifying the tool outputs are working as intended, save the installation. Otherwise the currently loaded installation is modified but the changes can be lost.'},
 {'machine': 'UR5e Cobot',
  'question': 'During quick system start-up, what must be verified on the Initialize Robot screen before pressing Start?',
  'gold_answer': 'Verify the payload mass in Active Payload and verify the mounting position is correct in the Robot field. Then tap Start to release the brake system.'},
 {'machine': 'UR5e Cobot',
  'question': 'What is the correct procedure for connecting a Teach Pendant to the Control Box?',
  'gold_answer': 'Do not connect or disconnect the Teach Pendant while the Control Box is powered on. Power off the Control Box before connecting the Teach Pendant, otherwise damage can occur.'},
 {'machine': 'UR5e Cobot',
  'question': 'When is the Safe Home Safety Output active, and how is the robot considered to be in the Safe Home Position?',
  'gold_answer': 'The Safe Home Safety Output is active when the robot is standing still at the Safe Home Position. The Robot Arm is in the Safe Home Position if the joint positions are at the specified joint angles or a multiple of 360 degrees thereof.'},
 {'machine': 'UR5e Cobot',
  'question': 'What can you do with the Home button in the Move tab, and what is its default action?',
  'gold_answer': 'The Home button opens the Move Robot into Position screen, where you can hold down Auto to move the robot into the position previously defined under Installation. By default, Home returns the Robot Arm to an upright position.'},
 {'machine': 'UR5e Cobot',
  'question': 'What happens in PolyScope if a program loses EtherNet/IP Scanner Device or PROFINET IO-Controller connection?',
  'gold_answer': 'You can configure the action as:\n- None: PolyScope ignores the lost connection and the program continues to run.\n- Pause: PolyScope pauses the current program and resumes from where it stopped.\n- Stop: PolyScope stops the current program.'},
 {'machine': 'UR5e Cobot',
  'question': 'How do you add the first waypoint versus additional waypoints in a robot program?',
  'gold_answer': 'To add the first waypoint, select where you want it in the Robot Program, then under Basic tap Move; a waypoint is added together with the Move node. To add more waypoints, select a Move node or Waypoint node and tap Waypoint under Basic.'},
 {'machine': 'UR5e Cobot',
  'question': 'What is the purpose of the Set Payload command, and what counts as payload on the UR5e?',
  'gold_answer': 'Set Payload configures the payload for the robot. Payload is the combined weight of everything attached to the robot tool flange. Setting it correctly helps prevent robot stops and ensures optimal robot movement.'},
 {'machine': 'UR5e Cobot',
  'question': 'When recovery mode is activated because a safety limit was exceeded, what are the recovery safety limits and what warning applies?',
  'gold_answer': 'In Recovery, you cannot run programs, but you can manually move the robot back within limits using Freedrive or the Move tab. The recovery limits are: Joint Speed Limit 30 °/s, Speed Limit 250 mm/s, Force Limit 100 N, Momentum Limit 10 kg m/s, and Power Limit 80 W. Use caution, because joint position limits, safety planes, and tool/end effector orientation limits are disabled in recovery mode.'},
 {'machine': 'UR5e Cobot',
  'question': 'What happens if you change something on the I/O Tab while a program is executing?',
  'gold_answer': 'The program stops if anything is changed during execution. At program stop, all output signals retain their states.'},
 {'machine': 'UR5e Cobot',
  'question': 'What are the mounting surface requirements when assembling the robot arm?',
  'gold_answer': 'Mount the robot arm on a sturdy, vibration-free surface. Verify the surface can withstand at least 10 times the full torque of the base joint and at least 5 times the weight of the robot arm.'},
 {'machine': 'UR5e Cobot',
  'question': 'What must be done before resetting an emergency stop push-button?',
  'gold_answer': 'Visually identify and assess the reason the E-stop was activated. Visual assessment of all equipment in the application is required, and the problem must be solved before resetting the push-button.'},
 {'machine': 'UR5e Cobot',
  'question': 'When the Tool Communication Interface (TCI) is enabled, what happens to the tool analog input?',
  'gold_answer': 'The tool analog input becomes unavailable when TCI is enabled.'},
 {'machine': 'UR5e Cobot',
  'question': 'How do you enable Backdrive using the Freedrive on robot function?',
  'gold_answer': 'On the Initialize screen, tap ON to start the power up sequence. When the robot state is Teach Pendant 3PE Stop, press and hold the Freedrive on robot. The robot state changes to Backdrive, and while the hold is maintained you can apply significant pressure to release the brake in a desired joint.'},
 {'machine': 'UR5e Cobot',
  'question': 'What happens if the robot is stopped or paused and then started using the Start input action?',
  'gold_answer': 'If stopped, the robot slowly moves to the first waypoint of the program before executing it. If paused, the robot slowly moves to the position where it was paused before resuming.'},
 {'machine': 'UR5e Cobot',
  'question': 'When can the safe home position output be activated, and what occurs if it is activated at the wrong position?',
  'gold_answer': 'The output can only be activated when the robot is in the configured and monitored safe home position. If the output is activated when the robot is not in that position, a category 0 stop is initiated.'},
 {'machine': 'UR5e Cobot',
  'question': 'How is the Home button used in the Move screen, and what is its default behavior?',
  'gold_answer': 'The Home button opens the Move Robot into Position screen, where you can hold down the Auto button to move the robot into the position previously defined under Installation. By default, Home returns the Robot Arm to an upright position.'},
 {'machine': 'UR5e Cobot',
  'question': 'What does the MODBUS signal connectivity status icon indicate, and what do the colors mean?',
  'gold_answer': 'It shows whether the signal can be properly read or written. Green means the signal is communicating properly, while gray means the unit responds unexpectedly or is not reachable.'},
 {'machine': 'UR5e Cobot',
  'question': 'Can the UR5e be put into service as supplied, or does it need further integration?',
  'gold_answer': 'It must be integrated into a final complete machine before being put into service. The integrator is responsible for ensuring the completed machine conforms with applicable directives and for providing the Declaration of Conformity.'}]

## Generate — Bridgeport Mill (target: 50 pairs)

10 batches × 5 pairs per batch = 50 target.

In [13]:
mill_results = []
for i in range(10):
    batch = generate_synthetic_qa(
        client,
        document_chunks=mill_chunks,
        golden_df=mill_golden,
        machine_name="Bridgeport Mill",
    )
    mill_results.extend(batch)
    print(f"  Batch {i+1:02d}: +{len(batch)} pairs  (running total: {len(mill_results)})")

print(f"\nBridgeport Mill total: {len(mill_results)} Q&A pairs generated")

  Batch 01: +5 pairs  (running total: 5)
  Batch 02: +5 pairs  (running total: 10)
  Batch 03: +5 pairs  (running total: 15)
  Batch 04: +5 pairs  (running total: 20)
  Batch 05: +5 pairs  (running total: 25)
  Batch 06: +5 pairs  (running total: 30)
  Batch 07: +5 pairs  (running total: 35)
  Batch 08: +5 pairs  (running total: 40)
  Batch 09: +5 pairs  (running total: 45)
  Batch 10: +5 pairs  (running total: 50)

Bridgeport Mill total: 50 Q&A pairs generated

## Combine and Save

In [14]:
all_results = ur5e_results + mill_results
df_out = pd.DataFrame(all_results, columns=["machine", "question", "gold_answer"])

OUT_CSV = Path("../data/QA/synthetic_qa_cobot_mill.csv")
df_out.to_csv(OUT_CSV, index=False)

print(f"Saved {len(df_out)} Q&A pairs to {OUT_CSV}")
print()
print(df_out["machine"].value_counts().to_string())

Saved 100 Q&A pairs to ../data/QA/synthetic_qa_cobot_mill.csv

machine
UR5e Cobot         50
Bridgeport Mill    50

## Preview

In [15]:
display(df_out.head(10))

,machine,question,gold_answer
0,UR5e Cobot,What must be provided as part of the electrica...,Provide:\n- Connection to ground\n- Main fuse\...
1,UR5e Cobot,What should you do before turning on the robot...,Plug and lock the cable from the robot into th...
2,UR5e Cobot,Why is it important to set the robot arm mount...,Specifying the mounting makes the Robot arm ap...
3,UR5e Cobot,What actions can PolyScope take if the robot l...,"The selectable actions are None, Pause, or Sto..."
4,UR5e Cobot,"What are the input voltage range, input freque...",Input voltage: 90–264 VAC. Input frequency: 47...
5,UR5e Cobot,How do you configure the robot to operate with...,"In Header, tap Installation, then Safety > Har..."
6,UR5e Cobot,What safety precaution is required when the Te...,The Emergency Stop button on the Teach Pendant...
7,UR5e Cobot,"When does the Safety Checksum change, and how ...",The Safety Checksum changes when Safety Functi...
8,UR5e Cobot,"What does the MODBUS Sequential mode do, and w...",Sequential mode forces the MODBUS client to wa...
9,UR5e Cobot,What is the warning for tool analog inputs in ...,Analog Inputs are not protected against over v...